---
- name: Create a new Demo EC2 instance
  hosts: localhost
  gather_facts: False

  vars:
      region: us-east-1
      instance_type: t2.micro
      ami: ami-0ff8a91507f77f867 # Ubuntu 16.04 LTS
      keypair: Mumbai # pem file name
      master_tag: Master
      slave_tag: Slave
      number_machines: 1
  
  tasks:
    - name: Create an ec2 instance
      ec2:
         key_name: "{{ keypair }}"
         group: default  # security group name
         instance_type: "{{ instance_type}}"
         image: "{{ ami }}"
         wait: true
         region: "{{ region }}"
         exact_count: "{{ number_machines }}"
         #count: 1  # default
         count_tag:
            Name: "{{ master_tag }}"
         instance_tags:
            Name: "{{ master_tag }}"
         vpc_subnet_id: subnet-0f4c7c58d2bd31d55
      register: ec2
    - debug:
        var: ec2.tagged_instances[0].public_dns_name
    
    - name: Wait for SSH to come up
      delegate_to: "{{ item.public_dns_name }}"
      wait_for_connection:
        delay: 10
        timeout: 320
        sleep: 5
      with_items:
        - "{{ ec2.tagged_instances }}"
        - "{{ ec2.instances }}"

    - name: Add new instance to host group
      add_host:
        hostname: "{{ item.public_dns_name }}"
        groupname: "{{ master_tag }}"
      with_items: 
        - "{{ ec2.tagged_instances }}"
        - "{{ ec2.instances }}"

- name: Configure instance(s)
  hosts: Master
  gather_facts: True
  become: true
  tasks:
    - name: install  git
      yum: name=git state=present












